добавил класс Task и скрипт index.php в задании Камень судьбы
htmlacademy-yii/901289-task-force-1 pull request #4
Opened 2019-11-10 03:58 UTC by SysoevEV

2019-11-11 09:59 UTC, vambus reviewed
Прошу убрать избыточную логику и переделать код с учётом комментариев. 
ТЗ же было такое:
1) определять список из всех доступных действий и статусов.
2) возвращать имя статуса, в который перейдёт задание после конкретного действия
Это первые два пункта, которые надо сделать в рамках этого задания.

Т.е. 
1) Определяем все доступные действия и статусы, каждое отдельной константой.
2) Делаем константу-карту действие => статус
Возвращаем статус в зависимости от действия.
Всё.
Лучше обсудить, конечно.

2019-11-11 09:59 UTC, tebazil commented on src/Task.php
> +    private $customer_id;
Можешь глянут ещё раз задание? Эти поля не входят в текущее задание :-)
Хотя вреда от них на текущий момент не вижу.

2019-11-11 09:59 UTC, tebazil commented on src/Task.php
> +    const USER_ROLE = [
Сложившаяся практика немного другая: мы пишем по одной константе на каждое значение, например:
`const USER_ROLE_CUSTOMER = 'role_customer'`
...
А потом складываем их в массивы, например:
`
const USER_ROLES = [
   self::USER_ROLE_CUSTOMER, self::USER_ROLE_ADMIN
]
`
Это помогает вынести простую логику из методов и сделать её более читабельной + получить рабочий автокомплит в некоторых ситуациях.

2019-11-11 09:59 UTC, tebazil commented on src/Task.php
> +    const USER_ROLE = [
Пример из рабочего проекта:

![Снимок экрана_2019-11-11_12-34-53](https://user-images.githubusercontent.com/2419721/68576747-b4dd9680-047f-11ea-91a3-6ea82e4f84ea.png)

(замечание: в этом примере вместо public static $var могло быть const)

2019-11-11 09:59 UTC, tebazil commented on src/Task.php
> +
Комментарий относится к обоим методам:
Подобный код хорошо оптимизировать выносом карт в константы:
```php
    const ACTION_CANCEL = 'action_cancel';
    const ACTION_RESPOND = 'action_respond';

    const STATUS_NEW = 'status_new';
    const STATUS_CANCELLED = 'status_cancelled';

    const ROLE_USER = 'role_user';
    const ROLE_EXECUTOR = 'role_executor';

    const NEXT_POSSIBLE_ACTION = [
      self::STATUS_NEW => [
          self::ROLE_USER => self::ACTION_CANCEL,
          self::ROLE_EXECUTOR => self::ACTION_RESPOND
          //...
      ],
    ];
```

2019-11-11 09:59 UTC, tebazil commented on src/Task.php
> +
Вышеописанное - просто пример. Плюс подхода - методы худеют и с ними проще работать.

2019-11-12 15:26 UTC, vambus requested changes
Вроде бы всё более-менее нормально (кроме нейминга), но давай ещё на этом этапе добавим тесты... 
Предлагаю:
1) Создать файл tests.php
2) В нем для каждого статуса добавить assert($a->getNextStatus(Task::ACTION_REFUSE), self::TASK_STATUS_FLUNK)
Ассерты - что-то вроде простых тестов. 
3) В php.ini `zend.assertions = 1` должно быть...
Проверь, что ассерты работают, скормив им assert, который должен выбросить ошибку.

2019-11-12 15:26 UTC, tebazil commented on src/Task.php
> +    const TASK_STATUS_NEW = "status_new";
Если у тебя класс называется Task, можно опустить префикс TASK_ у констант, тем самым ты повышаешь читабельность:
1) Извне: Task::STATUS_NEW vs Task::TASK_STATUS_NEW
2) Изнутри: self::STATUS_NEW vs self::TASK_STATUS_NEW

2019-11-12 15:26 UTC, tebazil commented on src/Task.php
> +    const TASK_STATUSES = [
Тоже можно сократить до STATUSES

2019-11-12 15:26 UTC, tebazil commented on src/Task.php
> +    const TASK_STATUS_FLUNK = "status_flunk";
flunk - это что за слово? проваленный? обычно используют слово failed

2019-11-12 15:26 UTC, tebazil commented on src/Task.php
> +        self::TASK_STATUS_FLUNK
По именованию, наверное, стоит отдельно поговорить по скайпу.. пока не буду сильно к этому привязываться.

2019-11-12 15:26 UTC, tebazil commented on index.php
>  ?>
Лучше не ставить закрывающий тэг, если он явно не нужен (такое может быть в случае, если за php кодом располагается html, например)

2019-11-12 15:28 UTC, tebazil commented on src/Task.php
> +    public function get_next_status ($action=self::ACTION_CANCEL)
Не нужно задавать действие по умолчанию.. если `$action` не передан - пусть будет ошибка, это лучше, чем тихо ошибку проигнорировать и посчитать, что мы хотим статус для действия отмены.

2019-11-13 14:48 UTC, tebazil commented
Спасибо! Отличная работа!

2019-11-13 14:53 UTC, merged